### ISSUE TITLE
NavGPT-2 Q-former weights of  Vicuna -7B and Vicuna -13B

### ISSUE THREAD

**Issue by yzqtszp02** [GengzeZhou/NavGPT-2#11]
Can you provide the  Q-former weights of  Vicuna -7B and Vicuna -13B. I tried to train with 4 4090 GPUs, but still reported CUDA out of memory. I have modified line 135 in dataloader_utils, def __init__(self, dataloader: DataLoader, use_distributed: bool = True): to load the data evenly, but still cannot train.

**Comment by yangxueyan0910** [comment]
sorry for cannot solve your problem,I’d like to ask you,can you implement the navigation of visual simulation environment through this code? It seems author used the headless mode in docker.请问你可以正常可视化仿真环境来inference导航过程了吗，我用docker在服务器上运行代码，但作者用了headless模式，我不知道是否可以实现可视化窗口渲染，还是开源的代码只能离屏渲染。

**Comment by GengzeZhou** [comment]
We haven’t implemented model or tensor parallelism in the Q-Former training code. The out-of-memory (OOM) issue on a 24GB GPU arises because the 7B model can't even forward a single sample—each step involves multiple image inputs, which significantly increases memory usage.

As for why the model weights aren’t released after forward, it's intentional: we don't consider extracting features from a decoder-based LLM to be a suitable solution in this context.

**Comment by GengzeZhou** [comment]
@yangxueyan0910 You could always [build MatterSim with -DEGL_RENDERING=ON](https://github.com/peteanderson80/Matterport3DSimulator) and render the original images.

An easy way for visualization is to record the trajectory inference by the policy and just render the observations at each step. You could refer to the [PREVALENT's visualization code](https://github.com/weituo12321/PREVALENT/blob/master/preprocess/walk_trajectories.ipynb).

**Comment by yzqtszp02** [comment]
> We haven’t implemented model or tensor parallelism in the Q-Former training code. The out-of-memory (OOM) issue on a 24GB GPU arises because the 7B model can't even forward a single sample—each step involves multiple image inputs, which significantly increases memory usage.
> 
> As for why the model weights aren’t released after forward, it's intentional: we don't consider extracting features from a decoder-based LLM to be a suitable solution in this context.

If I want to change the code for training Q-former to multi-GPUS training, which files or functions should I modify? I tried to use DDP directly in train.py. But it didn't work

**Comment by GengzeZhou** [comment]
Just change the `--nproc_per_node` in the [running script](https://github.com/GengzeZhou/NavGPT-2/blob/master/map_nav_src/models/run_scripts/train_NavGPT_xl.sh).

**Comment by yzqtszp02** [comment]
> Just change the `--nproc_per_node` in the [running script](https://github.com/GengzeZhou/NavGPT-2/blob/master/map_nav_src/models/run_scripts/train_NavGPT_xl.sh).
Directly changing --nproc_per_node does not work. I added some code to check.
init_distributed_mode(cfg.run_cfg)
local_rank = int(os.environ["LOCAL_RANK"])
 torch.cuda.set_device(local_rank)
print(f"Rank {local_rank}: Using GPU {torch.cuda.current_device()}")

The print result is Rank 0: Using GPU 0
The command I ran was： CUDA_VISIBLE_DEVICES=1,2,3 TOKENIZERS_PARALLELISM="false" torchrun --nproc_per_node=3 train.py --cfg-path lavis/projects/blip2/train/r2r_navgpt_ft_vicuna7b.yaml

**Comment by Wuwenji18** [comment]
> 很抱歉无法解决你的问题，我想问你，你能通过这段代码实现可视化模拟环境的导航吗？请问你可以正常可视化仿真环境来推断导航过程了吗，我用docker在服务器上运行代码，但作者用了headless模式，我不知道是否可以实现可视化窗口渲染，还是开源的代码只能离屏渲染。



> sorry for cannot solve your problem,I’d like to ask you,can you implement the navigation of visual simulation environment through this code? It seems author used the headless mode in docker.请问你可以正常可视化仿真环境来inference导航过程了吗，我用docker在服务器上运行代码，但作者用了headless模式，我不知道是否可以实现可视化窗口渲染，还是开源的代码只能离屏渲染。

Hi, I'm try to retry this program. Could you add my vx for talking? Thanks a lot!

**Comment by yangxueyan0910** [comment]
你好 我现在已经不做这个方向的课题研究了，但是当时弄的时候，他代码里确实只有headless模式，无法界面可视化，除非得自己修改代码，我当时没有弄出来


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GengzeZhou/NavGPT-2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年7月2日(星期三) 晚上9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GengzeZhou/NavGPT-2] NavGPT-2 Q-former weights of  Vicuna -7B and Vicuna -13B (Issue #11)



Wuwenji18 left a comment (GengzeZhou/NavGPT-2#11)
  
很抱歉无法解决你的问题，我想问你，你能通过这段代码实现可视化模拟环境的导航吗？请问你可以正常可视化仿真环境来推断导航过程了吗，我用docker在服务器上运行代码，但作者用了headless模式，我不知道是否可以实现可视化窗口渲染，还是开源的代码只能离屏渲染。
   
sorry for cannot solve your problem,I’d like to ask you,can you implement the navigation of visual simulation environment through this code? It seems author used the headless mode in docker.请问你可以正常可视化仿真环境来inference导航过程了吗，我用docker在服务器上运行代码，但作者用了headless模式，我不知道是否可以实现可视化窗口渲染，还是开源的代码只能离屏渲染。
  
Hi, I'm try to retry this program. Could you add my vx for talking? Thanks a lot!
